FROM rsplab-stream-server

ADD ./lite.properties ./lite.properties
ADD ./citybench.owl ./citybench.owl
ADD ./citybench-traffic.obda ./citybench-traffic.obda
ADD ./postgres.properties ./postgres.properties

RUN ls